version: '2'
services:
    gamesales-app:
        image: gamesales
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gamesales-postgresql:5432/GameSales
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gamesales-postgresql:
        extends:
            file: postgresql.yml
            service: gamesales-postgresql
